# Generated by Django 4.2.28 on 2026-02-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the friend', max_length=100)),
                ('nickname', models.CharField(help_text='Nickname or preferred name', max_length=50)),
                ('photo', models.ImageField(help_text='Profile photo of the friend', upload_to='friend_photos/')),
                ('memory_text', models.TextField(help_text='A short emotional note or memory about the friend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
                'ordering': ['name'],
            },
        ),
    ]
