# Generated by Django 4.2.28 on 2026-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='future_goal',
            field=models.CharField(blank=True, help_text='What do they want to become? (e.g., CEO, Traveler, Scientist)', max_length=200, null=True),
        ),
    ]
