# Generated by Django 4.2.28 on 2026-02-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0002_friend_future_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event name (e.g., Pongal Celebration, College Tour)', max_length=200)),
                ('cover_image', models.ImageField(help_text='Cover image for the event album', upload_to='event_covers/')),
                ('date', models.DateField(help_text='Date of the event')),
                ('description', models.TextField(blank=True, help_text='Short description of the event', null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo', upload_to='event_photos/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='The event this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='farewell.event')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
