# Generated by Django 4.2.28 on 2026-02-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0003_event_eventphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., First Day of College, Pongal Celebration', max_length=200)),
                ('date', models.DateField(help_text='When this happened')),
                ('description', models.TextField(help_text='What happened during this event')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this milestone', null=True, upload_to='timeline/')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SlamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Who is writing this message?', max_length=100)),
                ('message', models.TextField(help_text='The slam book message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(help_text='Who is this message for?', on_delete=django.db.models.deletion.CASCADE, related_name='slam_messages', to='farewell.friend')),
            ],
            options={
                'verbose_name': 'Slam Message',
                'verbose_name_plural': 'Slam Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The award name (e.g., Sothu Mootai, Silent Killer)', max_length=200)),
                ('icon_or_image', models.ImageField(blank=True, help_text='Optional icon/image for the award', null=True, upload_to='awards/')),
                ('winner', models.ForeignKey(help_text='The friend who won this award', on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='farewell.friend')),
            ],
            options={
                'verbose_name': 'Fun Award',
                'verbose_name_plural': 'Fun Awards',
            },
        ),
    ]
