# Generated by Django 4.2.28 on 2026-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0004_timelineevent_slammessage_funaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='signature_dialogue',
            field=models.CharField(blank=True, help_text='Their iconic catchphrase or quote', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='special_power',
            field=models.CharField(blank=True, help_text="Their superpower (e.g., Disappears when there's work)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='weakness',
            field=models.CharField(blank=True, help_text='Their kryptonite (e.g., Cannot say no to food)', max_length=100, null=True),
        ),
    ]
