# Generated by Django 4.2.28 on 2026-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0005_add_trading_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the staff member', max_length=100)),
                ('award_title', models.CharField(help_text="Their legendary title (e.g., 'Walking Encyclopedia', 'The Deadline Whisperer')", max_length=200)),
                ('famous_quote', models.TextField(help_text='Their most iconic dialogue, advice, or signature quote')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the staff member', null=True, upload_to='staff_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
    ]
