# Generated by Django 4.2.28 on 2026-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0006_add_staff_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Secret roll number for the Vault', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Secret roll number for the Vault', max_length=20, null=True, unique=True),
        ),
    ]
