# Generated by Django 5.2.11 on 2026-03-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0007_friend_roll_number_staff_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The confidential intel logged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_intels', to='farewell.friend')),
            ],
            options={
                'verbose_name': 'Secret Intel',
                'verbose_name_plural': 'Secret Intels',
                'ordering': ['-created_at'],
            },
        ),
    ]
