# Generated by Django 5.2.11 on 2026-03-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0008_secretintel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSecretMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The confidential message logged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_messages', to='farewell.staff')),
            ],
            options={
                'verbose_name': 'Staff Secret Message',
                'verbose_name_plural': 'Staff Secret Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
